# Generated by Django 4.2.3 on 2023-07-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="studentview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=38)),
                ("parent", models.CharField(max_length=38)),
                ("contact", models.CharField(max_length=38)),
                ("pincode", models.CharField(max_length=38)),
                ("email", models.CharField(max_length=38)),
                ("adress", models.CharField(max_length=38)),
            ],
        ),
    ]
