# Generated by Django 4.2.3 on 2023-07-29 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regproductapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="regview",
            old_name="phone",
            new_name="contact",
        ),
    ]
