# Generated by Django 4.2.3 on 2023-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regproductapp", "0002_rename_phone_regview_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="productview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=38)),
                ("pid", models.CharField(max_length=38)),
                ("pcat", models.CharField(max_length=38)),
                ("pprice", models.CharField(max_length=38)),
            ],
        ),
    ]
