# Generated by Django 4.2.3 on 2023-07-29 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regproductapp", "0003_productview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="productview",
            new_name="regproduct",
        ),
    ]
